- name: Demo on ansible variables - play level
  hosts: all
  vars:
    URL: play.sample.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}

- name: Demo on ansible variables - task level
  hosts: all
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}
      vars:
        URL: task.sample.com