- name: lookup ssm parameter store in nominated region
  hosts: localhost
  connection: local
  tasks:
  - name: Print a parameter
    ansible.builtin.debug:
      msg: Parameter - "{{ lookup('aws_ssm', 'test.sample', region='us-east-1' ) }}"